// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderservice.proto

package orderservice

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{0}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PingReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{1}
}
func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (dst *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(dst, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CreateOrderRequest struct {
	UserId               int64              `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TradeMode            int64              `protobuf:"varint,2,opt,name=trade_mode,json=tradeMode,proto3" json:"trade_mode,omitempty"`
	TradeType            int64              `protobuf:"varint,3,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	TradeSubType         int64              `protobuf:"varint,4,opt,name=trade_sub_type,json=tradeSubType,proto3" json:"trade_sub_type,omitempty"`
	AppId                string             `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	BusType              string             `protobuf:"bytes,6,opt,name=bus_type,json=busType,proto3" json:"bus_type,omitempty"`
	BusTradeNo           string             `protobuf:"bytes,7,opt,name=bus_trade_no,json=busTradeNo,proto3" json:"bus_trade_no,omitempty"`
	BusProducts          []*BusProductsList `protobuf:"bytes,8,rep,name=bus_products,json=busProducts,proto3" json:"bus_products,omitempty"`
	Currency             string             `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	TradeAmount          int64              `protobuf:"varint,10,opt,name=trade_amount,json=tradeAmount,proto3" json:"trade_amount,omitempty"`
	PayAmount            int64              `protobuf:"varint,11,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	Freight              int64              `protobuf:"varint,12,opt,name=freight,proto3" json:"freight,omitempty"`
	MerchantCoupon       int64              `protobuf:"varint,13,opt,name=merchant_coupon,json=merchantCoupon,proto3" json:"merchant_coupon,omitempty"`
	PlatformCoupon       int64              `protobuf:"varint,14,opt,name=platform_coupon,json=platformCoupon,proto3" json:"platform_coupon,omitempty"`
	ExpireTime           string             `protobuf:"bytes,15,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Remark               string             `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`
	TradeExtraInfo       string             `protobuf:"bytes,17,opt,name=trade_extra_info,json=tradeExtraInfo,proto3" json:"trade_extra_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{2}
}
func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (dst *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(dst, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateOrderRequest) GetTradeMode() int64 {
	if m != nil {
		return m.TradeMode
	}
	return 0
}

func (m *CreateOrderRequest) GetTradeType() int64 {
	if m != nil {
		return m.TradeType
	}
	return 0
}

func (m *CreateOrderRequest) GetTradeSubType() int64 {
	if m != nil {
		return m.TradeSubType
	}
	return 0
}

func (m *CreateOrderRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateOrderRequest) GetBusType() string {
	if m != nil {
		return m.BusType
	}
	return ""
}

func (m *CreateOrderRequest) GetBusTradeNo() string {
	if m != nil {
		return m.BusTradeNo
	}
	return ""
}

func (m *CreateOrderRequest) GetBusProducts() []*BusProductsList {
	if m != nil {
		return m.BusProducts
	}
	return nil
}

func (m *CreateOrderRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *CreateOrderRequest) GetTradeAmount() int64 {
	if m != nil {
		return m.TradeAmount
	}
	return 0
}

func (m *CreateOrderRequest) GetPayAmount() int64 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *CreateOrderRequest) GetFreight() int64 {
	if m != nil {
		return m.Freight
	}
	return 0
}

func (m *CreateOrderRequest) GetMerchantCoupon() int64 {
	if m != nil {
		return m.MerchantCoupon
	}
	return 0
}

func (m *CreateOrderRequest) GetPlatformCoupon() int64 {
	if m != nil {
		return m.PlatformCoupon
	}
	return 0
}

func (m *CreateOrderRequest) GetExpireTime() string {
	if m != nil {
		return m.ExpireTime
	}
	return ""
}

func (m *CreateOrderRequest) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *CreateOrderRequest) GetTradeExtraInfo() string {
	if m != nil {
		return m.TradeExtraInfo
	}
	return ""
}

type BusProductsList struct {
	BusType              string     `protobuf:"bytes,1,opt,name=bus_type,json=busType,proto3" json:"bus_type,omitempty"`
	ProductType          string     `protobuf:"bytes,2,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	CommodityId          string     `protobuf:"bytes,3,opt,name=commodity_id,json=commodityId,proto3" json:"commodity_id,omitempty"`
	CommodityName        string     `protobuf:"bytes,4,opt,name=commodity_name,json=commodityName,proto3" json:"commodity_name,omitempty"`
	BusOrderNo           string     `protobuf:"bytes,5,opt,name=bus_order_no,json=busOrderNo,proto3" json:"bus_order_no,omitempty"`
	GoodsAmount          int64      `protobuf:"varint,6,opt,name=goods_amount,json=goodsAmount,proto3" json:"goods_amount,omitempty"`
	PayAmount            int64      `protobuf:"varint,7,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	SupplierCode         int64      `protobuf:"varint,8,opt,name=supplier_code,json=supplierCode,proto3" json:"supplier_code,omitempty"`
	PurchaseAmount       int64      `protobuf:"varint,9,opt,name=purchase_amount,json=purchaseAmount,proto3" json:"purchase_amount,omitempty"`
	ExtraInfo            string     `protobuf:"bytes,10,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	FeeList              []*FeeInfo `protobuf:"bytes,11,rep,name=fee_list,json=feeList,proto3" json:"fee_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BusProductsList) Reset()         { *m = BusProductsList{} }
func (m *BusProductsList) String() string { return proto.CompactTextString(m) }
func (*BusProductsList) ProtoMessage()    {}
func (*BusProductsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{3}
}
func (m *BusProductsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusProductsList.Unmarshal(m, b)
}
func (m *BusProductsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusProductsList.Marshal(b, m, deterministic)
}
func (dst *BusProductsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusProductsList.Merge(dst, src)
}
func (m *BusProductsList) XXX_Size() int {
	return xxx_messageInfo_BusProductsList.Size(m)
}
func (m *BusProductsList) XXX_DiscardUnknown() {
	xxx_messageInfo_BusProductsList.DiscardUnknown(m)
}

var xxx_messageInfo_BusProductsList proto.InternalMessageInfo

func (m *BusProductsList) GetBusType() string {
	if m != nil {
		return m.BusType
	}
	return ""
}

func (m *BusProductsList) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func (m *BusProductsList) GetCommodityId() string {
	if m != nil {
		return m.CommodityId
	}
	return ""
}

func (m *BusProductsList) GetCommodityName() string {
	if m != nil {
		return m.CommodityName
	}
	return ""
}

func (m *BusProductsList) GetBusOrderNo() string {
	if m != nil {
		return m.BusOrderNo
	}
	return ""
}

func (m *BusProductsList) GetGoodsAmount() int64 {
	if m != nil {
		return m.GoodsAmount
	}
	return 0
}

func (m *BusProductsList) GetPayAmount() int64 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *BusProductsList) GetSupplierCode() int64 {
	if m != nil {
		return m.SupplierCode
	}
	return 0
}

func (m *BusProductsList) GetPurchaseAmount() int64 {
	if m != nil {
		return m.PurchaseAmount
	}
	return 0
}

func (m *BusProductsList) GetExtraInfo() string {
	if m != nil {
		return m.ExtraInfo
	}
	return ""
}

func (m *BusProductsList) GetFeeList() []*FeeInfo {
	if m != nil {
		return m.FeeList
	}
	return nil
}

type FeeInfo struct {
	FeeType              int64    `protobuf:"varint,1,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`
	Fee                  int64    `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeInfo) Reset()         { *m = FeeInfo{} }
func (m *FeeInfo) String() string { return proto.CompactTextString(m) }
func (*FeeInfo) ProtoMessage()    {}
func (*FeeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{4}
}
func (m *FeeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeInfo.Unmarshal(m, b)
}
func (m *FeeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeInfo.Marshal(b, m, deterministic)
}
func (dst *FeeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeInfo.Merge(dst, src)
}
func (m *FeeInfo) XXX_Size() int {
	return xxx_messageInfo_FeeInfo.Size(m)
}
func (m *FeeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FeeInfo proto.InternalMessageInfo

func (m *FeeInfo) GetFeeType() int64 {
	if m != nil {
		return m.FeeType
	}
	return 0
}

func (m *FeeInfo) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type CreateOrderReply struct {
	TradeNo              string         `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	BusTradeNo           string         `protobuf:"bytes,2,opt,name=bus_trade_no,json=busTradeNo,proto3" json:"bus_trade_no,omitempty"`
	OrderNos             []*OrderNoList `protobuf:"bytes,3,rep,name=orderNos,proto3" json:"orderNos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateOrderReply) Reset()         { *m = CreateOrderReply{} }
func (m *CreateOrderReply) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReply) ProtoMessage()    {}
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{5}
}
func (m *CreateOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReply.Unmarshal(m, b)
}
func (m *CreateOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReply.Marshal(b, m, deterministic)
}
func (dst *CreateOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReply.Merge(dst, src)
}
func (m *CreateOrderReply) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReply.Size(m)
}
func (m *CreateOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReply proto.InternalMessageInfo

func (m *CreateOrderReply) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

func (m *CreateOrderReply) GetBusTradeNo() string {
	if m != nil {
		return m.BusTradeNo
	}
	return ""
}

func (m *CreateOrderReply) GetOrderNos() []*OrderNoList {
	if m != nil {
		return m.OrderNos
	}
	return nil
}

type OrderNoList struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	BusOrderNo           string   `protobuf:"bytes,2,opt,name=bus_order_no,json=busOrderNo,proto3" json:"bus_order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderNoList) Reset()         { *m = OrderNoList{} }
func (m *OrderNoList) String() string { return proto.CompactTextString(m) }
func (*OrderNoList) ProtoMessage()    {}
func (*OrderNoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{6}
}
func (m *OrderNoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderNoList.Unmarshal(m, b)
}
func (m *OrderNoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderNoList.Marshal(b, m, deterministic)
}
func (dst *OrderNoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderNoList.Merge(dst, src)
}
func (m *OrderNoList) XXX_Size() int {
	return xxx_messageInfo_OrderNoList.Size(m)
}
func (m *OrderNoList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderNoList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderNoList proto.InternalMessageInfo

func (m *OrderNoList) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *OrderNoList) GetBusOrderNo() string {
	if m != nil {
		return m.BusOrderNo
	}
	return ""
}

type WxPayRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TradeNo              string   `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PayAmount            int64    `protobuf:"varint,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	PayType              string   `protobuf:"bytes,4,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ClientIp             string   `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	AppId                string   `protobuf:"bytes,7,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ProductId            string   `protobuf:"bytes,8,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SceneInfo            string   `protobuf:"bytes,9,opt,name=scene_info,json=sceneInfo,proto3" json:"scene_info,omitempty"`
	ReceiptSymbol        string   `protobuf:"bytes,10,opt,name=receipt_symbol,json=receiptSymbol,proto3" json:"receipt_symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxPayRequest) Reset()         { *m = WxPayRequest{} }
func (m *WxPayRequest) String() string { return proto.CompactTextString(m) }
func (*WxPayRequest) ProtoMessage()    {}
func (*WxPayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{7}
}
func (m *WxPayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxPayRequest.Unmarshal(m, b)
}
func (m *WxPayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxPayRequest.Marshal(b, m, deterministic)
}
func (dst *WxPayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxPayRequest.Merge(dst, src)
}
func (m *WxPayRequest) XXX_Size() int {
	return xxx_messageInfo_WxPayRequest.Size(m)
}
func (m *WxPayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WxPayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WxPayRequest proto.InternalMessageInfo

func (m *WxPayRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *WxPayRequest) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

func (m *WxPayRequest) GetPayAmount() int64 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *WxPayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *WxPayRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WxPayRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *WxPayRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *WxPayRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *WxPayRequest) GetSceneInfo() string {
	if m != nil {
		return m.SceneInfo
	}
	return ""
}

func (m *WxPayRequest) GetReceiptSymbol() string {
	if m != nil {
		return m.ReceiptSymbol
	}
	return ""
}

type WXPayReply struct {
	PrepayId             string   `protobuf:"bytes,1,opt,name=prepay_id,json=prepayId,proto3" json:"prepay_id,omitempty"`
	CodeUrl              string   `protobuf:"bytes,2,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`
	MwebUrl              string   `protobuf:"bytes,3,opt,name=mweb_url,json=mwebUrl,proto3" json:"mweb_url,omitempty"`
	AppId                string   `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NonceStr             string   `protobuf:"bytes,6,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`
	Package              string   `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
	SignType             string   `protobuf:"bytes,8,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	PaySign              string   `protobuf:"bytes,9,opt,name=pay_sign,json=paySign,proto3" json:"pay_sign,omitempty"`
	MchId                string   `protobuf:"bytes,10,opt,name=mch_id,json=mchId,proto3" json:"mch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WXPayReply) Reset()         { *m = WXPayReply{} }
func (m *WXPayReply) String() string { return proto.CompactTextString(m) }
func (*WXPayReply) ProtoMessage()    {}
func (*WXPayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{8}
}
func (m *WXPayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WXPayReply.Unmarshal(m, b)
}
func (m *WXPayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WXPayReply.Marshal(b, m, deterministic)
}
func (dst *WXPayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WXPayReply.Merge(dst, src)
}
func (m *WXPayReply) XXX_Size() int {
	return xxx_messageInfo_WXPayReply.Size(m)
}
func (m *WXPayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WXPayReply.DiscardUnknown(m)
}

var xxx_messageInfo_WXPayReply proto.InternalMessageInfo

func (m *WXPayReply) GetPrepayId() string {
	if m != nil {
		return m.PrepayId
	}
	return ""
}

func (m *WXPayReply) GetCodeUrl() string {
	if m != nil {
		return m.CodeUrl
	}
	return ""
}

func (m *WXPayReply) GetMwebUrl() string {
	if m != nil {
		return m.MwebUrl
	}
	return ""
}

func (m *WXPayReply) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *WXPayReply) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *WXPayReply) GetNonceStr() string {
	if m != nil {
		return m.NonceStr
	}
	return ""
}

func (m *WXPayReply) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *WXPayReply) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *WXPayReply) GetPaySign() string {
	if m != nil {
		return m.PaySign
	}
	return ""
}

func (m *WXPayReply) GetMchId() string {
	if m != nil {
		return m.MchId
	}
	return ""
}

type AliPayRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TradeNo              string   `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PayAmount            int64    `protobuf:"varint,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	PayType              string   `protobuf:"bytes,4,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ReturnUrl            string   `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	BuyerId              string   `protobuf:"bytes,8,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	ReceiptSymbol        string   `protobuf:"bytes,9,opt,name=receipt_symbol,json=receiptSymbol,proto3" json:"receipt_symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliPayRequest) Reset()         { *m = AliPayRequest{} }
func (m *AliPayRequest) String() string { return proto.CompactTextString(m) }
func (*AliPayRequest) ProtoMessage()    {}
func (*AliPayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{9}
}
func (m *AliPayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliPayRequest.Unmarshal(m, b)
}
func (m *AliPayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliPayRequest.Marshal(b, m, deterministic)
}
func (dst *AliPayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliPayRequest.Merge(dst, src)
}
func (m *AliPayRequest) XXX_Size() int {
	return xxx_messageInfo_AliPayRequest.Size(m)
}
func (m *AliPayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AliPayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AliPayRequest proto.InternalMessageInfo

func (m *AliPayRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AliPayRequest) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

func (m *AliPayRequest) GetPayAmount() int64 {
	if m != nil {
		return m.PayAmount
	}
	return 0
}

func (m *AliPayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *AliPayRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AliPayRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AliPayRequest) GetReturnUrl() string {
	if m != nil {
		return m.ReturnUrl
	}
	return ""
}

func (m *AliPayRequest) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *AliPayRequest) GetReceiptSymbol() string {
	if m != nil {
		return m.ReceiptSymbol
	}
	return ""
}

type AliPayReply struct {
	H5Html               string         `protobuf:"bytes,1,opt,name=H5_html,json=H5Html,proto3" json:"H5_html,omitempty"`
	AliTradeNo           string         `protobuf:"bytes,2,opt,name=ali_trade_no,json=aliTradeNo,proto3" json:"ali_trade_no,omitempty"`
	AppReply             *AlipayAppInfo `protobuf:"bytes,3,opt,name=appReply,proto3" json:"appReply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AliPayReply) Reset()         { *m = AliPayReply{} }
func (m *AliPayReply) String() string { return proto.CompactTextString(m) }
func (*AliPayReply) ProtoMessage()    {}
func (*AliPayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{10}
}
func (m *AliPayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliPayReply.Unmarshal(m, b)
}
func (m *AliPayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliPayReply.Marshal(b, m, deterministic)
}
func (dst *AliPayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliPayReply.Merge(dst, src)
}
func (m *AliPayReply) XXX_Size() int {
	return xxx_messageInfo_AliPayReply.Size(m)
}
func (m *AliPayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AliPayReply.DiscardUnknown(m)
}

var xxx_messageInfo_AliPayReply proto.InternalMessageInfo

func (m *AliPayReply) GetH5Html() string {
	if m != nil {
		return m.H5Html
	}
	return ""
}

func (m *AliPayReply) GetAliTradeNo() string {
	if m != nil {
		return m.AliTradeNo
	}
	return ""
}

func (m *AliPayReply) GetAppReply() *AlipayAppInfo {
	if m != nil {
		return m.AppReply
	}
	return nil
}

type AlipayAppInfo struct {
	Charset              string   `protobuf:"bytes,1,opt,name=charset,proto3" json:"charset,omitempty"`
	SignType             string   `protobuf:"bytes,2,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	NotifyUrl            string   `protobuf:"bytes,4,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Timestamp            string   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Method               string   `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`
	ProductCode          string   `protobuf:"bytes,8,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	BizContent           string   `protobuf:"bytes,9,opt,name=biz_content,json=bizContent,proto3" json:"biz_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlipayAppInfo) Reset()         { *m = AlipayAppInfo{} }
func (m *AlipayAppInfo) String() string { return proto.CompactTextString(m) }
func (*AlipayAppInfo) ProtoMessage()    {}
func (*AlipayAppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_orderservice_fc811d6d9227a65a, []int{11}
}
func (m *AlipayAppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlipayAppInfo.Unmarshal(m, b)
}
func (m *AlipayAppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlipayAppInfo.Marshal(b, m, deterministic)
}
func (dst *AlipayAppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlipayAppInfo.Merge(dst, src)
}
func (m *AlipayAppInfo) XXX_Size() int {
	return xxx_messageInfo_AlipayAppInfo.Size(m)
}
func (m *AlipayAppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AlipayAppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AlipayAppInfo proto.InternalMessageInfo

func (m *AlipayAppInfo) GetCharset() string {
	if m != nil {
		return m.Charset
	}
	return ""
}

func (m *AlipayAppInfo) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *AlipayAppInfo) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *AlipayAppInfo) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *AlipayAppInfo) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *AlipayAppInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AlipayAppInfo) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AlipayAppInfo) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *AlipayAppInfo) GetBizContent() string {
	if m != nil {
		return m.BizContent
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "orderservice.PingRequest")
	proto.RegisterType((*PingReply)(nil), "orderservice.PingReply")
	proto.RegisterType((*CreateOrderRequest)(nil), "orderservice.CreateOrderRequest")
	proto.RegisterType((*BusProductsList)(nil), "orderservice.busProductsList")
	proto.RegisterType((*FeeInfo)(nil), "orderservice.FeeInfo")
	proto.RegisterType((*CreateOrderReply)(nil), "orderservice.CreateOrderReply")
	proto.RegisterType((*OrderNoList)(nil), "orderservice.orderNoList")
	proto.RegisterType((*WxPayRequest)(nil), "orderservice.WxPayRequest")
	proto.RegisterType((*WXPayReply)(nil), "orderservice.WXPayReply")
	proto.RegisterType((*AliPayRequest)(nil), "orderservice.AliPayRequest")
	proto.RegisterType((*AliPayReply)(nil), "orderservice.AliPayReply")
	proto.RegisterType((*AlipayAppInfo)(nil), "orderservice.AlipayAppInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	// ping 测试连通性
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// 创建订单
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	// 微信支付
	WxPay(ctx context.Context, in *WXPayReply, opts ...grpc.CallOption) (*WxPayRequest, error)
	// 支付宝支付
	AliPay(ctx context.Context, in *AliPayReply, opts ...grpc.CallOption) (*AliPayRequest, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/orderservice.OrderService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, "/orderservice.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) WxPay(ctx context.Context, in *WXPayReply, opts ...grpc.CallOption) (*WxPayRequest, error) {
	out := new(WxPayRequest)
	err := c.cc.Invoke(ctx, "/orderservice.OrderService/WxPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AliPay(ctx context.Context, in *AliPayReply, opts ...grpc.CallOption) (*AliPayRequest, error) {
	out := new(AliPayRequest)
	err := c.cc.Invoke(ctx, "/orderservice.OrderService/AliPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	// ping 测试连通性
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// 创建订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	// 微信支付
	WxPay(context.Context, *WXPayReply) (*WxPayRequest, error)
	// 支付宝支付
	AliPay(context.Context, *AliPayReply) (*AliPayRequest, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderservice.OrderService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderservice.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_WxPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WXPayReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).WxPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderservice.OrderService/WxPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).WxPay(ctx, req.(*WXPayReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AliPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliPayReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AliPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orderservice.OrderService/AliPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AliPay(ctx, req.(*AliPayReply))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderservice.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OrderService_Ping_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "WxPay",
			Handler:    _OrderService_WxPay_Handler,
		},
		{
			MethodName: "AliPay",
			Handler:    _OrderService_AliPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderservice.proto",
}

func init() { proto.RegisterFile("orderservice.proto", fileDescriptor_orderservice_fc811d6d9227a65a) }

var fileDescriptor_orderservice_fc811d6d9227a65a = []byte{
	// 1202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xc1, 0x8f, 0xdb, 0xc4,
	0x17, 0xee, 0x26, 0xbb, 0xb1, 0xfd, 0x9c, 0xdd, 0xee, 0xcf, 0x52, 0x7f, 0xf5, 0x66, 0x59, 0xba,
	0x0d, 0x54, 0xf4, 0x54, 0xa1, 0xa2, 0xc2, 0x05, 0x09, 0xca, 0x0a, 0xd4, 0x20, 0x28, 0x25, 0x5b,
	0x54, 0x6e, 0x96, 0x63, 0x4f, 0x92, 0x51, 0x6d, 0xcf, 0x30, 0x1e, 0x97, 0x75, 0x6f, 0x5c, 0xb8,
	0x71, 0x46, 0x42, 0x1c, 0xf9, 0x1f, 0xf8, 0x47, 0xf8, 0x83, 0xd0, 0x7b, 0x33, 0x76, 0xec, 0x64,
	0x29, 0x47, 0x6e, 0x99, 0xef, 0x7b, 0x76, 0x66, 0xbe, 0xef, 0x7b, 0x6f, 0x0c, 0x81, 0x50, 0x29,
	0x53, 0x25, 0x53, 0xaf, 0x78, 0xc2, 0x1e, 0x48, 0x25, 0xb4, 0x08, 0xc6, 0x5d, 0x6c, 0x7a, 0x07,
	0xfc, 0x67, 0xbc, 0x58, 0xcd, 0xd9, 0x0f, 0x15, 0x2b, 0x75, 0x70, 0x0c, 0xc3, 0xbc, 0x5c, 0x85,
	0x7b, 0xe7, 0x7b, 0xf7, 0xbd, 0x39, 0xfe, 0x9c, 0x9e, 0x81, 0x67, 0x0a, 0x64, 0x56, 0x5f, 0x43,
	0xff, 0xb5, 0x0f, 0xc1, 0x85, 0x62, 0xb1, 0x66, 0xdf, 0xe0, 0x6b, 0x9b, 0xf7, 0xdc, 0x06, 0xa7,
	0x2a, 0x99, 0x8a, 0x78, 0x4a, 0xc5, 0xc3, 0xf9, 0x08, 0x97, 0xb3, 0x34, 0x38, 0x03, 0xd0, 0x2a,
	0x4e, 0x59, 0x94, 0x8b, 0x94, 0x85, 0x03, 0xe2, 0x3c, 0x42, 0xbe, 0x16, 0x29, 0xdb, 0xd0, 0xba,
	0x96, 0x2c, 0x1c, 0x76, 0xe8, 0xe7, 0xb5, 0x64, 0xc1, 0xbb, 0x70, 0x64, 0xe8, 0xb2, 0x5a, 0x98,
	0x92, 0x7d, 0x2a, 0x19, 0x13, 0x7a, 0x59, 0x2d, 0xa8, 0xea, 0x16, 0x8c, 0x62, 0x29, 0xf1, 0xbf,
	0x0f, 0x68, 0xa3, 0x07, 0xb1, 0x94, 0xb3, 0x34, 0x38, 0x01, 0x77, 0x51, 0x95, 0xe6, 0xb1, 0x11,
	0x11, 0xce, 0xa2, 0x2a, 0xe9, 0x89, 0x73, 0x18, 0x13, 0x45, 0xef, 0x2e, 0x44, 0xe8, 0x10, 0x0d,
	0x48, 0x23, 0xf4, 0x54, 0x04, 0x9f, 0x9a, 0x0a, 0xa9, 0x44, 0x5a, 0x25, 0xba, 0x0c, 0xdd, 0xf3,
	0xe1, 0x7d, 0xff, 0xe1, 0xd9, 0x83, 0x9e, 0xc0, 0x8b, 0xaa, 0x7c, 0x66, 0x0b, 0xbe, 0xe2, 0xa5,
	0x9e, 0xfb, 0x1d, 0x20, 0x98, 0x80, 0x9b, 0x54, 0x4a, 0xb1, 0x22, 0xa9, 0x43, 0x8f, 0xde, 0xdf,
	0xae, 0x83, 0xbb, 0x60, 0x4e, 0x10, 0xc5, 0xb9, 0xa8, 0x0a, 0x1d, 0x02, 0x9d, 0xca, 0x27, 0xec,
	0x31, 0x41, 0xa8, 0x8c, 0x8c, 0xeb, 0xa6, 0xc0, 0x37, 0xca, 0xc8, 0xb8, 0xb6, 0x74, 0x08, 0xce,
	0x52, 0x31, 0xbe, 0x5a, 0xeb, 0x70, 0x4c, 0x5c, 0xb3, 0x0c, 0xde, 0x83, 0x9b, 0x39, 0x53, 0xc9,
	0x3a, 0x2e, 0x74, 0x94, 0x88, 0x4a, 0x8a, 0x22, 0x3c, 0xa4, 0x8a, 0xa3, 0x06, 0xbe, 0x20, 0x14,
	0x0b, 0x65, 0x16, 0xeb, 0xa5, 0x50, 0x79, 0x53, 0x78, 0x64, 0x0a, 0x1b, 0xd8, 0x16, 0xde, 0x01,
	0x9f, 0x5d, 0x49, 0xae, 0x58, 0xa4, 0x79, 0xce, 0xc2, 0x9b, 0x46, 0x2c, 0x03, 0x3d, 0xe7, 0x39,
	0x0b, 0xfe, 0x0f, 0x23, 0xc5, 0xf2, 0x58, 0xbd, 0x0c, 0x8f, 0x89, 0xb3, 0xab, 0xe0, 0x3e, 0x1c,
	0x9b, 0x63, 0xb2, 0x2b, 0xad, 0xe2, 0x88, 0x17, 0x4b, 0x11, 0xfe, 0x8f, 0x2a, 0x8c, 0xad, 0x9f,
	0x23, 0x3c, 0x2b, 0x96, 0x62, 0xfa, 0xfb, 0x10, 0x6e, 0x6e, 0xa9, 0xd9, 0xf3, 0x6f, 0xaf, 0xef,
	0xdf, 0x5d, 0x18, 0x5b, 0x67, 0x0c, 0x3d, 0x20, 0xda, 0xb7, 0x58, 0x53, 0x92, 0x88, 0x3c, 0x17,
	0x29, 0xd7, 0x35, 0x46, 0x63, 0x68, 0x4a, 0x5a, 0x6c, 0x96, 0x06, 0xf7, 0xe0, 0x68, 0x53, 0x52,
	0xc4, 0xb9, 0x49, 0x97, 0x37, 0x3f, 0x6c, 0xd1, 0xa7, 0x71, 0xde, 0x86, 0x85, 0x9c, 0xc7, 0xb0,
	0x1c, 0xb4, 0x61, 0xa1, 0x16, 0x78, 0x2a, 0xf0, 0xbf, 0x56, 0x42, 0xa4, 0x65, 0xe3, 0xd6, 0xc8,
	0xd8, 0x49, 0xd8, 0xb5, 0x76, 0x3a, 0xdb, 0x76, 0xbe, 0x03, 0x87, 0x65, 0x25, 0x65, 0xc6, 0x99,
	0x8a, 0x12, 0xec, 0x14, 0xd7, 0xe4, 0xbc, 0x01, 0x2f, 0xb0, 0x59, 0xd0, 0xb0, 0x0a, 0x2d, 0x2c,
	0xdb, 0xe0, 0x78, 0xd6, 0x30, 0x0b, 0x6f, 0xfe, 0xac, 0xa3, 0x38, 0xd0, 0x7e, 0x3d, 0xd6, 0x88,
	0x1d, 0xbc, 0x0f, 0xee, 0x92, 0xb1, 0x28, 0xe3, 0x25, 0x06, 0x0b, 0x73, 0x7d, 0xab, 0x9f, 0xeb,
	0x2f, 0x18, 0xc3, 0xc2, 0xb9, 0xb3, 0x64, 0x0c, 0xad, 0x98, 0x7e, 0x08, 0x8e, 0xc5, 0xd0, 0x15,
	0x7c, 0xb8, 0x75, 0x65, 0x48, 0x55, 0x24, 0xf9, 0x31, 0x0c, 0x97, 0xac, 0x69, 0x72, 0xfc, 0x39,
	0xfd, 0x79, 0x0f, 0x8e, 0x7b, 0xd3, 0x02, 0x87, 0xca, 0x09, 0xb8, 0x6d, 0xe3, 0x59, 0x5f, 0xb5,
	0xed, 0xba, 0xed, 0xbe, 0x1c, 0xec, 0xf4, 0xe5, 0x23, 0x70, 0x85, 0x51, 0xbd, 0x0c, 0x87, 0xb4,
	0xf7, 0x93, 0xfe, 0xde, 0x2d, 0x4b, 0xfd, 0xd8, 0x96, 0x4e, 0xbf, 0x04, 0xbf, 0x43, 0xe0, 0x16,
	0x5a, 0x3b, 0xed, 0x16, 0x2c, 0xbd, 0xe3, 0xf6, 0x60, 0xdb, 0xed, 0xe9, 0x9f, 0x03, 0x18, 0xbf,
	0xb8, 0x7a, 0x16, 0xd7, 0xff, 0x3a, 0xfc, 0xba, 0x27, 0x1d, 0xf4, 0x4f, 0xda, 0xcf, 0xc3, 0x70,
	0x3b, 0x0f, 0x27, 0xe0, 0x22, 0xdd, 0x8e, 0x3c, 0x6f, 0xee, 0xc8, 0xb8, 0xb6, 0xb3, 0xcb, 0x4f,
	0x59, 0x99, 0x28, 0x2e, 0x35, 0x17, 0x85, 0x4d, 0x63, 0x17, 0x0a, 0x4e, 0xc1, 0x4b, 0x32, 0xce,
	0x0a, 0x1d, 0x71, 0x69, 0x27, 0x9f, 0x6b, 0x80, 0x99, 0xec, 0x0c, 0x4b, 0xa7, 0x3b, 0x2c, 0x71,
	0x3f, 0xb6, 0xa3, 0x78, 0x4a, 0xe9, 0xf3, 0xe6, 0x9e, 0x45, 0x0c, 0x5d, 0x26, 0xac, 0x60, 0x26,
	0x51, 0x66, 0x9c, 0x79, 0x84, 0x50, 0x28, 0xee, 0xc1, 0x91, 0x62, 0x09, 0xe3, 0x52, 0x47, 0x65,
	0x9d, 0x2f, 0x44, 0x66, 0x43, 0x77, 0x68, 0xd1, 0x4b, 0x02, 0xa7, 0xbf, 0x0d, 0x00, 0x5e, 0x7c,
	0x4f, 0xca, 0x61, 0x10, 0x4e, 0xc1, 0x93, 0x8a, 0xe1, 0x39, 0xad, 0x72, 0xde, 0xdc, 0x35, 0x80,
	0xd1, 0x0e, 0x1b, 0x21, 0xaa, 0x54, 0xd6, 0x68, 0x87, 0xeb, 0xef, 0x54, 0x86, 0x54, 0xfe, 0x23,
	0x5b, 0x10, 0x65, 0xda, 0xda, 0xc1, 0x35, 0x52, 0x9b, 0xd3, 0xed, 0x77, 0x4f, 0xf7, 0x16, 0x78,
	0x38, 0xba, 0x4a, 0x1d, 0xe7, 0xd2, 0x2a, 0xb6, 0x01, 0x70, 0x1f, 0x85, 0x28, 0x12, 0x16, 0x95,
	0x5a, 0x35, 0x7a, 0x11, 0x70, 0xa9, 0x15, 0x0e, 0x5a, 0x19, 0x27, 0x2f, 0xe3, 0x15, 0xb3, 0x82,
	0x35, 0x4b, 0x7c, 0xac, 0xe4, 0xab, 0xc2, 0x98, 0x64, 0x14, 0x73, 0x11, 0x20, 0x97, 0xac, 0x81,
	0xb8, 0xb6, 0x72, 0xa1, 0x81, 0x97, 0x7c, 0x55, 0xe0, 0x1e, 0xf3, 0x64, 0x8d, 0x7b, 0x34, 0x22,
	0x1d, 0xe4, 0xc9, 0x7a, 0x96, 0x4e, 0x7f, 0x1d, 0xc0, 0xe1, 0xe3, 0x8c, 0xff, 0x67, 0xb9, 0xfa,
	0x87, 0x5b, 0x74, 0x2b, 0x6e, 0xa3, 0xdd, 0xb8, 0x9d, 0x01, 0x28, 0xa6, 0x2b, 0x55, 0x90, 0x21,
	0x46, 0x24, 0xcf, 0x20, 0xd6, 0xad, 0x45, 0x55, 0x9b, 0x63, 0xb8, 0xcd, 0x18, 0xaf, 0xe9, 0x1c,
	0xbb, 0xb1, 0xf1, 0xae, 0x8b, 0xcd, 0x4f, 0x7b, 0xe0, 0x37, 0xca, 0x60, 0x6e, 0x6e, 0x83, 0xf3,
	0xe4, 0x51, 0xb4, 0xd6, 0x79, 0x66, 0x53, 0x33, 0x7a, 0xf2, 0xe8, 0x89, 0xce, 0x33, 0xec, 0xdd,
	0x38, 0xe3, 0x3b, 0xe3, 0x23, 0xce, 0x78, 0x33, 0x3e, 0x3e, 0x02, 0x37, 0x96, 0x92, 0x5e, 0x43,
	0xe2, 0xf8, 0x0f, 0x4f, 0xfb, 0xe3, 0xe3, 0x71, 0xc6, 0x51, 0x2d, 0x29, 0x69, 0x00, 0xb6, 0xc5,
	0xd3, 0x5f, 0x8c, 0x3b, 0x1b, 0x0e, 0x83, 0x91, 0xac, 0x63, 0x55, 0x32, 0xdd, 0x8c, 0x10, 0xbb,
	0xec, 0x07, 0x63, 0xb0, 0x15, 0x8c, 0x00, 0xf6, 0x29, 0x14, 0x26, 0xb8, 0xf4, 0x1b, 0x15, 0x2c,
	0x84, 0xe6, 0xcb, 0x9a, 0x14, 0x34, 0xbe, 0x78, 0x06, 0x41, 0x05, 0xdf, 0x9c, 0xde, 0x10, 0x9c,
	0x57, 0x4c, 0x95, 0x1b, 0x73, 0x9a, 0x25, 0x5e, 0xcb, 0x39, 0xd3, 0x6b, 0xd1, 0xb4, 0xba, 0x5d,
	0x75, 0x6f, 0xcf, 0xf6, 0xae, 0xd9, 0xdc, 0x9e, 0x74, 0xd5, 0xdc, 0x01, 0x7f, 0xc1, 0x5f, 0x47,
	0x89, 0x28, 0x34, 0xb3, 0xd7, 0x0c, 0x0e, 0x41, 0xfe, 0xfa, 0xc2, 0x20, 0x0f, 0xff, 0x18, 0xc0,
	0x98, 0x06, 0xe2, 0xa5, 0x11, 0x2e, 0xf8, 0x18, 0xf6, 0xf1, 0xbb, 0x31, 0xd8, 0x1a, 0xc7, 0x9d,
	0x8f, 0xcd, 0xc9, 0xed, 0xeb, 0x28, 0x14, 0xf7, 0x46, 0xf0, 0x2d, 0xf8, 0x9d, 0x7b, 0x22, 0x38,
	0xef, 0x57, 0xee, 0x7e, 0x70, 0x4e, 0xde, 0x7e, 0x43, 0x85, 0x79, 0xe5, 0x27, 0x70, 0x40, 0x53,
	0x3a, 0x08, 0xfb, 0xa5, 0x9b, 0x01, 0x34, 0x99, 0x6c, 0x31, 0x9d, 0xa1, 0x3e, 0xbd, 0x11, 0x7c,
	0x06, 0x23, 0x93, 0xba, 0xed, 0x33, 0x75, 0xb2, 0x38, 0x39, 0xbd, 0x9e, 0xb2, 0xef, 0x58, 0x8c,
	0xe8, 0x1b, 0xfc, 0x83, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xa0, 0xec, 0x74, 0x99, 0x0b,
	0x00, 0x00,
}
